name: Post to Mastodon on new blog

on:
  push:
    paths:
      - "src/content/blog/**/*.md"

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v44

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run script if new files
        if: steps.changed.outputs.added_files != ''
        run: node scripts/postToMastodon.js ${{ steps.changed.outputs.all_changed_files }}
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
